/*
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PowerState;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * LightData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-18T13:17:03.092764+02:00[Europe/Berlin]")public class LightData {

  @SerializedName("id")
  private String id = null;

  @SerializedName("power_state")
  private PowerState powerState = null;
  public LightData id(String id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  public LightData powerState(PowerState powerState) {
    this.powerState = powerState;
    return this;
  }

  

  /**
  * Get powerState
  * @return powerState
  **/
  @Schema(description = "")
  public PowerState getPowerState() {
    return powerState;
  }
  public void setPowerState(PowerState powerState) {
    this.powerState = powerState;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LightData lightData = (LightData) o;
    return Objects.equals(this.id, lightData.id) &&
        Objects.equals(this.powerState, lightData.powerState);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, powerState);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LightData {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    powerState: ").append(toIndentedString(powerState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
