/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.LightData;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-05-18T13:17:07.324917+02:00[Europe/Berlin]")
@Api(value = "light", description = "the light API")
public interface LightApi {

    @ApiOperation(value = "Returns the light unit data.", nickname = "lightGet", notes = "", response = LightData.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A light data object.", response = LightData.class),
        @ApiResponse(code = 200, message = "Unexpected error") })
    @RequestMapping(value = "/light",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<LightData> lightGet();


    @ApiOperation(value = "Set the light unit data.", nickname = "lightPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Set successful."),
        @ApiResponse(code = 200, message = "Unexpected error") })
    @RequestMapping(value = "/light",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> lightPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody LightData body);

}
